# Generated by Django 3.2.7 on 2021-09-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='author',
        ),
    ]
